### ISSUE TITLE
Groups/Themes issues

### ISSUE THREAD

**Issue by riccardoerra** [smallmedia/iod-ckan#44]
- [x] `Group name already exists in database`, how to really delete a theme?
- [x] `resource_url_upload` preset doesn't work for groups using `scheming` plugin?

**Comment by goranmaxim** [comment]
The *_delete calls simply mark the object as 'deleted', the purge operation(s) remove the object from the database. 
http://docs.ckan.org/en/ckan-2.6.3/api/index.html#ckan.logic.action.delete.group_purge

**Comment by riccardoerra** [comment]
Managed to purge a theme. Closing this.
