### ISSUE TITLE
Remove facets from the search sidebars

### ISSUE THREAD

**Issue by kmbn** [smallmedia/iod-ckan#48]
To remove facets, or change their names, use the IFacets plugin interface. You'll find the relevant documentation here: http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IFacets

To use IFacets to remove facet `foo` from the dataset search sidebar, you would:

1. Add IFacets to the plugins implemented by your theme's plugin class.
 If you imported `ckan.plugins`  as plugins, then you would add the line `plugins.implements(plugins.IFacets)` to your class.
2. Add a method to the class called `dataset_facets(self, facets_dict, package_type)`. The method will return the modified `facets_dict`. If your portal only has one type of dataset (which is usually the case), you can ignore `package_type` (though don't remove it).

So to remove the facet `foo`, the method would look like this:

```
def dataset_facets(self, facets_dict, package_type):
    """Update the facets used on dataset search pages."""
    facets_dict.pop('foo')
    return facets_dict
```

**Comment by riccardoerra** [comment]
Facet is removed only for datasets list page
How to remove facet from all the search sidebar, like for example datasets list for a specific group page?

**Comment by kmbn** [comment]
Did you try the `group_facets` method described in the IFacets documentation? See http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IFacets.group_facets for more information
