### ISSUE TITLE
Themes translation

### ISSUE THREAD

**Issue by nimaadib** [smallmedia/iod-ckan#54]
re:Tags and themes not getting translated. [#46](https://github.com/smallmedia/iod-ckan/issues/46)

To translate the themes ([here](http://new.iranopendata.org/theme) for example) we need a list of Themes (En and Fa for each one) to complete the translation file.

**Comment by brobertzadeh** [comment]
@nimaadib I have asked the project lead for the list and will add it here asap

**Comment by brobertzadeh** [comment]
| Theme Translations |  
-- | -- | --
1 | Art and Culture and Tourism | هنر، فرهنگ و گردشگری
2 | Banking and Finance | مالی و بانکی
3 | Budget and Government Spending | بودجه و هزینه‌های دولت
4 | Communications | ارتباطات
5 | Economic Sector | بخش‌های اقتصادی
6 | Education | آموزش
7 | Employment | اشتغال
8 | Energy | انرژی
9 | Environment | محیط زیست
10 | Health | بهداشت
11 | Housing | مسکن
12 | Population | جمعیت
13 | Trade | تجارت
14 | Transport | حمل و نقل

**Comment by nimaadib** [comment]
the themes translation changes did not completely done in this branch. I will push the edited snippet.
