### ISSUE TITLE
"url" field is missing in resource form

### ISSUE THREAD

**Issue by nimaadib** [smallmedia/iod-ckan#55]
There is an error in the last step of adding a package. The "url" field is missing in resource form: `ckan/templates/package/snippets/resource_form.html`

It seems we need to have an input field like this:
`<input name="url" value="http://test.com" type="hidden"/>`

Do you have the same issue in the production?

**Comment by brobertzadeh** [comment]
If you haven't already, it's definitely worth joining the [ckan dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) and also taking a look through issues (open and closed) on the [main ckan repository](https://github.com/ckan/ckan/issues?utf8=%E2%9C%93&q=is%3Aissue) , they're a wealth of information!

@nimaadib are you able to share a screen grab of the error message with us so @chogarcia can take a look or describe exactly what is happening so we can try and replicate?
