### ISSUE TITLE
Pull request for new IOD

### ISSUE THREAD

**Issue by brobertzadeh** [smallmedia/iod-ckan#56]
Hi @nimaadib and @kamal-kosari 
I have been in touch with our support dev Chó and he has set up a branch for you to submit a pull request to:
https://github.com/smallmedia/iod-ckan/tree/iod-a19

If you have made a lot of changes, it would be great if you could submit the PRs in manageable chunks for us to review, perhaps against the related issue numbers for instance? Or just with descriptions so we know what to look out for 

Let us know here if you have any questions, and please tag @chogarcia so he gets a notification too

**Comment by nimaadib** [comment]
Hi @brobertzadeh  and @chogarcia 

I just submitted a PR [#58](https://github.com/smallmedia/iod-ckan/pull/58). I will submit other PRs like this, if it's ok.

**Comment by chogarcia** [comment]
I would suggest we keep PRs small, one per task if possible so then it is easier to track over time.

**Comment by brobertzadeh** [comment]
@chogarcia can you please confirm if you're able to run the -a19 branch and if we can get this set up as a testing server soon? What are the next steps? 

(ref: @nimaadib )
