### ISSUE TITLE
Change/redirect URL for reports

### ISSUE THREAD

**Issue by nimaadib** [smallmedia/iod-ckan#64]
On the current IOD website there is a place to promote articles online from other sources that have referenced IOD data. At the moment, there are a number of articles (Shokoufeh has the links) that are linking to / referencing IOD datasets on the current website. This means that when the new website is launched, these links will be broken. For that list of links that Shokoufeh has, redirects need to be set up.

**Comment by nimaadib** [comment]
Shokoufeh:

> I went though the links you sent me, here is the links for old datasets and new ones. (https://docs.google.com/spreadsheets/d/1jVqsqjwGvwwIb80p4r6nfJ8yjZWz2C8sPyuu7n3Q1Iw/edit#gid=0) Let me know if there is any problem or question with them.

**Comment by nimaadib** [comment]
Dear @chogarcia ,

I think we can use nginx redirect to cover this issue. for example:

`rewrite ^/fa/datasets/cbibf161/ /fa_IR/dataset/price-consumer-goods-services-urban-years-1369-1394 permanent;`

I can edit the nginx config file in the Ansible role and add the list of redirects. any comment?

**Comment by chogarcia** [comment]
Not sure if this is within the scope @brobertzadeh.
Ideally we would migrate this project to Docker and remove Ansible.
