### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by nimaadib** [smallmedia/iod-ckan#68]
* Add social networks links

**Comment by nimaadib** [comment]
@brobertzadeh please let me know which social networks you want to add to the pages.
I will add the links to the footer.

**Comment by brobertzadeh** [comment]
@nimaadib I've asked Shokou by email, hope to get a reply soon

**Comment by nimaadib** [comment]
Shokoufeh:

Here are the links for IOD social media pages:
IG: https://www.instagram.com/iranopendata/ 
FB: https://www.facebook.com/opendatairan
Twitter: https://twitter.com/iranopendata
Telegram: https://t.me/IranOpenData
