### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by nimaadib** [smallmedia/iod-ckan#69]
- [ ]  Better styling for responsive
Needs thorough testing on mobile to ensure it is seamless, fast loading, fully featured

- [ ]   Remove shadow and rounder corners for all pages
As per image below
![image](https://user-images.githubusercontent.com/11687372/52776594-dd904700-3039-11e9-8bba-2af9058e33a2.png)

- [ ]   Clean and organise CSS
Make sure CSS / SCSS files are commented, variables are well-structured, redundant code is tidied up etc

**Comment by nimaadib** [comment]
@brobertzadeh could you please let me know if you see any specific problem in the pages regarding the "Better styling for responsive" item?

**Comment by brobertzadeh** [comment]
@nimaadib can we park this item until we have a staging server up for the iod-a19 branch? Then we can make a list of responsive styling changes?
