### ISSUE TITLE
deploying the new version

### ISSUE THREAD

**Issue by nimaadib** [smallmedia/iod-ckan#87]
Dear @chogarcia ,

Shokoufeh asked me to deploy the new version on the production server (aka the NEW subdomain: http://new.iranopendata.org/fa_IR/).

As I don't have access to your infrastructure, could you please check with Shokoufeh and @brobertzadeh and tell me what we can do?

**Comment by nimaadib** [comment]
@chogarcia @brobertzadeh could you please advise on this issue?

**Comment by brobertzadeh** [comment]
@nimaadib, sorry that @chogarcia seems to have gone awol, we're trying to contact him. We're also getting a new setup with a technical services company that should be able to help with this, but, quick question, if you are just wanting to deploy to the new.iranopendata subdomain, do you just need to merge your code into the branch of code which is currently the production server?

**Comment by nimaadib** [comment]
I already submitted a [Pull Request](https://github.com/smallmedia/iod-ckan/pull/86) to merge a few commits into iod-v2.6 from iod-a19.
But it would not affect the new.iranopendata subdomain till someone update the codes on your server.
